### ISSUE TITLE
A TypeError occurred while running training scripts.

### ISSUE THREAD

**Issue by 0sure** [PeterWang512/GANSketching#14]
When I was running `bash scripts/train_teaser_cat.sh` in my Linux server, I got a **TypeError**. My virtual environment in conda already installed: **Python 3.7.12, pytorch 1.7.1, cudatoolkit 10.1.243, torchvision 0.8.2, and ninja 1.10.2**. I already tried higher version of pytorch 1.8.1, but it has another problem of subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status. So I returned to the **pytorch 1.7.1** environment. I have been troubled by the TypeError problem for several days. Can someone help me solve it? Thanks.

Logs in detail:
```
(test3) yuanWang@server-TiTan:~/GANtest1$ bash scripts/train_teaser_cat.sh
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from eval import Evaluator
  File "/data4/yuanWang/GANtest1/eval/__init__.py", line 1, in <module>
    from .evaluation import Evaluator
  File "/data4/yuanWang/GANtest1/eval/evaluation.py", line 7, in <module>
    from run_metrics import get_vgg_features, make_eval_images
  File "/data4/yuanWang/GANtest1/run_metrics.py", line 13, in <module>
    from training.networks.stylegan2 import Generator
  File "/data4/yuanWang/GANtest1/training/networks/__init__.py", line 2, in <module>
    from .misc import *
  File "/data4/yuanWang/GANtest1/training/networks/misc.py", line 1, in <module>
    from . import stylegan2
  File "/data4/yuanWang/GANtest1/training/networks/stylegan2.py", line 8, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/data4/yuanWang/GANtest1/training/networks/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/data4/yuanWang/GANtest1/training/networks/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/data4/yuanWang/anaconda3/envs/test3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/data4/yuanWang/anaconda3/envs/test3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1269, in _jit_compile
    is_standalone=is_standalone,
TypeError: bump_version_if_changed() got an unexpected keyword argument 'is_python_module'
```

**Comment by PeterWang512** [comment]
Maybe try removing your cache? It should be in `~/.cache/torch_extensions/`

**Comment by 0sure** [comment]
Hello! I tried removing all cache file in `/.cache/torch_extensions/` and all generated cache folder named `__pycache__` in code folder. I renamed GANSketching folder to GANtest1 to storage code. After that, I got the identical error logs.

After the last run, I opened the `fused` folder in `/.cache/torch_extensions/` and found no file in it. It was empty.

Could you please tell me if your code was compiled and executed in Linux environment? If I directly use the CUDA operator you have compiled, can I make the code run normally? Thanks! @PeterWang512

**Comment by PeterWang512** [comment]
Directly using the compiled code might not work, because I think each machines can have different compiled code. You might want to check this thread to make sure if you are able to make a PyTorch CUDA extension: https://github.com/rosinality/stylegan2-pytorch/issues/1#issuecomment-674079837

**Comment by 0sure** [comment]
I tried to copy the `op` folder in the subfolder to the home directory, and then run `python fused_ act.py `in virtual environment. After that, I entered `~ /cache/torch_ Extensions / fused` folder, used `ninja -f build.ninja` command to complete compilation manually. Thanks for your help these days! @PeterWang512
