### ISSUE TITLE
ImportError: No module named 'fused'

### ISSUE THREAD

**Issue by UangBell** [PeterWang512/GANSketching#16]
Hi Wang,

Thanks for sharing your code.

I have installed all the prerequisite packages. When I try to compile the module **'fused'**, errors below occur. I removed all cache file in `torch_extensions` folder by using `rm -rf` before every building tests but still got the same error. By the way I already changed `'['ninja', '-v']'` to `'['ninja', '--version']'` in cpp_extension.py under `anaconda3/envs/CTtest1/lib/python3.7/site-packages/torch/utils/` to avoid another error. Could you please tell me how to fix it?

```
Detected CUDA files, patching ldflags
Emitting ninja build file /home/slhua/.cache/torch_extensions/fused/build.ninja...
Building extension module fused...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.7.2
Loading extension module fused...
Traceback (most recent call last):
  File "fused_act.py", line 25, in <module>
    is_python_module = True)
  File "/home/slhua/anaconda3/envs/CTtest1/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "/home/slhua/anaconda3/envs/CTtest1/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1213, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/slhua/anaconda3/envs/CTtest1/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1560, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/slhua/anaconda3/envs/CTtest1/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
```

My environment:
cudatoolkit 10.2.89, cudnn 7.6.5, python 3.7.6, pytorch 1.7.1, torchvision 0.8.2, ninja 1.7.2

**Comment by PeterWang512** [comment]
Seems like you might not have nvcc installed. You might want to check this thread: https://github.com/rosinality/stylegan2-pytorch/issues/1#issuecomment-674079837
Maybe you can check if you are able to build pytorch cuda extensions first?
