### ISSUE TITLE
running Evaluations without GPU and CUDA 

### ISSUE THREAD

**Issue by apathros** [PeterWang512/GANSketching#5]
Hi Thank you for providing the code,

I am trying to run the evaluation's on Windows without GPU and CUDA support.  when i run the the python file

python run_metrics.py --models_list weights/eval_list --output metric_results.csv --device=cpu

_Traceback (most recent call last):
  File "run_metrics.py", line 12, in <module>
    from eval.ppl import compute_ppl
  File "C:\Users\\Downloads\Test\eval\__init__.py", line 1, in <module>
    from .evaluation import Evaluator
  File "C:\Users\\Downloads\Test\eval\evaluation.py", line 7, in <module>
    from run_metrics import get_vgg_features, make_eval_images
  File "C:\Users\\Downloads\Test\run_metrics.py", line 13, in <module>
    from training.networks.stylegan2 import Generator
  File "C:\Users\\Downloads\Test\training\networks\__init__.py", line 2, in <module>
    from .misc import *
  File "C:\Users\\Downloads\Test\training\networks\misc.py", line 1, in <module>
    from . import stylegan2
  File "C:\Users\\Downloads\Test\training\networks\stylegan2.py", line 8, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\\Downloads\Test\training\networks\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\\Downloads\Test\training\networks\op\fused_act.py", line 15, in <module>
    **os.path.join(module_path, "fused_bias_act_kernel.cu"),**
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 1091, in load
    keep_intermediates=\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 1385, in _write_ninja_file_and_build_library
    is_standalone)
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 1484, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib/x64")}')
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 1982, in _join_cuda_home
    **raise EnvironmentError('CUDA_HOME environment variable is not set. '**
**OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root._**

Is CUDA and GPU is mandatory to run the evaluation ?

**Comment by PeterWang512** [comment]
Yes, the current implementation will require CUDA.
